#pragma config(Sensor, in1,    rlight,         sensorReflection)
#pragma config(Sensor, in2,    midlight,       sensorReflection)
#pragma config(Sensor, in3,    llight,         sensorReflection)
#pragma config(Sensor, dgtl1,  ultrasonic,     sensorSONAR_mm)
#pragma config(Motor,  port1,           rfront,        tmotorVex269, openLoop)
#pragma config(Motor,  port2,           rback,         tmotorVex269, openLoop)
#pragma config(Motor,  port3,           lfront,        tmotorVex269, openLoop)
#pragma config(Motor,  port4,           lback,         tmotorVex269, openLoop)
#pragma config(Motor,  port5,           rollers,       tmotorVex269, openLoop)
#pragma config(Motor,  port6,           rarmbot,       tmotorVex269, openLoop)
#pragma config(Motor,  port7,           rarmtop,       tmotorVex269, openLoop)
#pragma config(Motor,  port8,           larmbot,       tmotorVex269, openLoop)
#pragma config(Motor,  port9,           larmtop,       tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int applesauce;
	int low1;
	int low2;
	int high;
	int threshold;

	while(true)
	{
		//Wait for 1/2 sec then go full speed with rollers for 3 seconds, turn 180, go full speed for 3 seconds, turn 180 again, return to code
		//if(SensorValue(ultrasonic)</*insert value here*/)
		//{
		//	wait1Msec(500)
		//	motor[rfront]=120;
		//	motor[rback]=120;
		//	motor[lfront]=-120;
		//	motor[rfront]=-120;
		//  motor[rollers]=120;
		//	wait1Msec(3000)
		//
		//	wait1Msec(500)
		//
		//	motor[rfront]=-120;
		//	motor[rback]=-120;
		//	motor[lfront]=120;
		//	motor[rfront]=120;
		//	wait1Msec(3000)
		//
	  //  wait1Msec(500)
		//}
		//else
		//{
		//	/*insert line following code here*/
		//}

		motor[rfront]=vexRT[Ch2];   //driver control
		motor[rback]=vexRT[Ch2];
		motor[lfront]=-vexRT[Ch2];
		motor[lback]=-vexRT[Ch2];

		motor[rfront]=vexRT[Ch4];
		motor[rback]=vexRT[Ch4];
		motor[lfront]=vexRT[Ch4];
		motor[lback]=vexRT[Ch4];

		if(vexRT[Btn5U]==1)
		{
			motor[rarmtop]=120;
			motor[rarmbot]=120;
			motor[larmtop]=-120;
			motor[larmbot]=-120;
		}
		else if(vexRT[Btn5D]==1)
		{
			motor[rarmtop]=-120;
			motor[rarmbot]=-120;
			motor[larmtop]=120;
			motor[larmbot]=120;
		}
		else
		{
			motor[rarmtop]=0;
			motor[rarmbot]=0;
			motor[larmtop]=0;
			motor[larmbot]=0;
		}
		if(vexRT[Btn6U]==1)
		{
			motor[rollers]=120;
		}
		else if(vexRT[Btn6D])
		{
			motor[rollers]=-120;
		}
		else
		{
			motor[rollers]=0;
		}

		if(vexRT[Btn8U]==1)
		{
			applesauce=1;
			low1=SensorValue(rlight);
			low2=SensorValue(llight);
			high=SensorValue(midlight);
			threshold=(((low1+low2)/2)+high)/2;



		  while(applesauce==1)   //line following
			{
				if(SensorValue(midlight)>threshold && SensorValue(rlight)<threshold && SensorValue(llight)<threshold)
				{
					motor[port1]=50;
					motor[port2]=50;
					motor[port3]=-50;
					motor[port4]=-50;
				}
				else if(SensorValue(rlight)>threshold)
				{
					motor[port1]=10;
					motor[port2]=10;
					motor[port3]=-50;
					motor[port4]=-50;
				}
				else if(SensorValue(llight)>threshold)
				{
					motor[port1]=50;
					motor[port2]=50;
					motor[port3]=-10;
					motor[port4]=-10;
				}
				else
				{
					motor[port1]=0;
					motor[port2]=0;
					motor[port3]=0;
					motor[port4]=0;
				}
				if(vexRT[Btn8D]==1)
				{
					applesauce=0;
				}
			}
		}
	}
}
