#pragma config(Motor,  port1,           lefttop,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftbot,      tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightbot,       tmotorVex393, openLoop)
#pragma config(Motor,  port4,           righttop,       tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armr1,         tmotorVex393, openLoop)
#pragma config(Motor,  port6,           armr2,         tmotorVex393, openLoop)
#pragma config(Motor,  port7,           arml1,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           arml2,         tmotorVex393, openLoop)
#pragma config(Motor,  port9,           score,         tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
	motor(lefttop) = vexRT[ch3];
	motor(leftbot) = -vexRT[ch3];
	motor(rightbot) = vexRT[ch2];
	motor(righttop) = -vexRT[ch2];

		if(vexRT[Btn6U]==1)
		{
			motor[armr1] = motor[armr2] = 127;
			motor[arml1] = motor[arml2] = -127;
		}
		else
		{
			motor[armr1] = motor[armr2] = 0;
			motor[arml1] = motor[arml2] = 0;
		}
		if(vexRT[Btn6D]==1)
	  {
	  	motor[armr1] = motor[armr2] = -127;
			motor[arml1] = motor[arml2] = 127;
		}
		else
	  {
	  	motor[armr1] = motor[armr2] = 0;
			motor[arml1] = motor[arml2] = 0;
		}

		if(vexRT[Btn5U]==1)
		{
			motor[score] = -127;
		}
		else
		{
			motor[score] = 0;
		}
		if(vexRT[Btn5D]==1)
		{
			motor[score] = 127;
		}
		else
		{
			motor[score] = 0;
		}
	}
}
