#pragma config(Motor,  port1,           lefttop,       tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftbot,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           rightbot,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           righttop,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           armr1,         tmotorVex393, openLoop)
#pragma config(Motor,  port6,           armr2,         tmotorVex393, openLoop)
#pragma config(Motor,  port7,           arml1,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           arml2,         tmotorVex393, openLoop)
#pragma config(Motor,  port9,           score,         tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}


task autonomous()
{
	motor[leftbot] = motor[rightbot] = -127;
	motor[lefttop] = motor[righttop] = 127;
	wait10Msec(200);
	motor[lefttop] = motor[rightbot] = 0;
	motor[leftbot] = motor[righttop] = 0;
}

task usercontrol()
{
	while(true)
	{
	  motor[righttop] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
    motor[rightbot] =  vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
    motor[lefttop] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
    motor[leftbot] =  vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];


		if(vexRT[Btn6U]==1)
		{
			motor[armr1] = motor[armr2] = 127;
			motor[arml1] = motor[arml2] = -127;
			wait10Msec(10);
		}
		else
		{
			motor[armr1] = motor[armr2] = 0;
			motor[arml1] = motor[arml2] = 0;
		}
		if(vexRT[Btn6D]==1)
	  {
	  	motor[armr1] = motor[armr2] = -127;
			motor[arml1] = motor[arml2] = 127;
			wait10Msec(10);
		}
		else
	  {
	  	motor[armr1] = motor[armr2] = 0;
			motor[arml1] = motor[arml2] = 0;
		}

		if(vexRT[Btn5U]==1)
		{
			motor[score] = -127;
			wait10Msec(10);
		}
		else
		{
			motor[score] = 0;
		}
		if(vexRT[Btn5D]==1)
		{
			motor[score] = 127;
			wait10Msec(10);
		}
		else
		{
			motor[score] = 0;
		}
	}
}
