#pragma config(Motor,  port2,           Shooting1,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int count;
	while(1)
	{
		count=127;
		if(vexRT[Btn8R]==1)
		{	motor[port2]=count;	}
		else
		{ motor[port2]=0;	}
	}
}
